const themeToMoodMap = {
  Adventure: "competitive",
  Action: "competitive",
  Relaxing: "relaxed",
  Challenging: "competitive",
  "Dark Fantasy": "competitive",
  Platform: "happy",
  Puzzle: "relaxed",
  Kids: "happy",
  Racing: "competitive",
  Arcade: "happy",
  Sandbox: "relaxed",
  "Open world": "relaxed",
  Shooter: "competitive",
  Warfare: "competitive",
  "Science fiction": "competitive",
  Indie: "relaxed",
  Simulator: "relaxed",
  Sport: "competitive",
  "Non-fiction": "relaxed",
  "Role-playing (RPG)": "relaxed",
  Strategy: "competitive",
  "Turn-based strategy (TBS)": "competitive",
  "4X (explore, expand, exploit, exterminate)": "competitive",
  "Visual Novel": "relaxed",
  Drama: "relaxed",
  Fantasy: "relaxed",
  Historical: "relaxed",
  Party: "happy",
  Comedy: "happy",
  Horror: "competitive",
  Survival: "competitive",
  Tactical: "competitive",
  Music: "happy",
  Fighting: "competitive",
  Educational: "relaxed",
  Stealth: "competitive",
  "Quiz/Trivia": "happy",
  "Real Time Strategy (RTS)": "competitive",
  "Point-and-click": "relaxed",
  Mystery: "relaxed",
};

export default themeToMoodMap;
